### ISSUE TITLE
Import error: No module named MarkupSafe

### ISSUE THREAD

**Issue by VenuNarukulla** [vfarcic/docker-swarm-blue-green#1]
When I run the ansible command first time, there is an error saying "`Import error: No module named MarkupSafe`"

This was resolved by running
`pip install markupsafe`

Using Ubunty\ trusty64 as vivid64 is not avaialble

**Comment by vfarcic** [comment]
Can you send a pull request with the changes?

**Comment by vfarcic** [comment]
Ansible and Docker PIP were very old. I updated them and everything seem to be working correctly. Feel free to re-open this ticket if you experience any problem.

As a side note, this repo sets up the old standalone Swarm. You should probably use the new Swarm Mode bundled in Docker 1.12.
